version: "3"

services:
  react-app:
    build: ./react-app
    expose:
      - 3000
  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_HOST: db
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://localhost/wordpress');
        define('WP_SITEURL', 'http://localhost/wordpress');
    expose:
      - 80
    depends_on:
      - db

  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - react-app
      - wordpress

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
