import styles from "@/styles/Home.module.css";
import { Inter } from "@next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function SpecialPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="http://localhost/wp-includes/blocks/navigation/style.min.css"
        />
      </Head>
      <main className={styles.main}>
        <h1>Does something special 2</h1>
      </main>
    </>
  );
}
